apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}
  service:
    name: {{ .Values.app.name }}
    port: 80
    targetPort: 8080
    gateways:
      - {{ .Values.app.name }}-gateway
    hosts:
      - "*"
  analysis:
    interval: {{ .Values.canary.interval }}
    threshold: {{ .Values.canary.threshold }}
    maxWeight: {{ .Values.canary.maxWeight }}
    stepWeight: {{ .Values.canary.stepWeight }}
    metrics:
      - name: success-rate
        threshold: {{ .Values.canary.successRate }}
        interval: {{ .Values.canary.interval }}
        query: |
          sum(rate(http_requests_total{status=~"2.."}[1m])) /
          sum(rate(http_requests_total[1m])) * 100
{{- if .Values.canary.blackbox.enabled }}
      - name: availability
        threshold: {{ .Values.canary.blackbox.threshold }}
        interval: {{ .Values.canary.interval }}
        query: |
          avg(probe_success{instance=~"http://{{ .Values.app.name }}.{{ .Values.namespace }}.svc.cluster.local.*"}) * 100
{{- end }}