config:
  modules:
    http_2xx:
      prober: http
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        valid_status_codes: [200]
        method: GET
    http_post_2xx:
      prober: http
      http:
        method: POST
        valid_status_codes: [200]

 
serviceMonitor:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi