apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.scrape_interval }}

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: {{ toJson .Values.config.scrape_targets }}

      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [{{ .Values.config.blackbox.module }}]
        static_configs:
          - targets: {{ toJson .Values.config.blackbox.targets }}
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: {{ .Values.config.blackbox.service }}