apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: canary-demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'myapp'
        static_configs:
          - targets: ['localhost:8080']
        metrics_path: '/actuator/prometheus'